services:
  php:
    build:
      context: .
      dockerfile: Dockerfile.php
      target: final
    develop:
      watch:
        - action: sync
          path: ./
          target: /var/www/html

    extra_hosts:
      - host.docker.internal:host-gateway
    networks:
      - dokploy-network

  nginx:
    image: nginx
    ports:
      - "6969:80"
    volumes:
      - ./src:/var/www/html/src/
      - ./public:/var/www/html/public/
      - ./docker/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
    networks:
      - dokploy-network

networks:
  dokploy-network:
    external: true
