services:
  php:
    build:
      context: .
      dockerfile: Dockerfile.php
      target: development
    develop:
      watch:
        - action: sync
          path: ./
          target: /var/www/html

    extra_hosts:
      - host.docker.internal:host-gateway

  nginx:
    image: nginx
    ports:
      - "3434:80"
    volumes:
      - ./src:/var/www/html/src/
      - ./public:/var/www/html/public/
      - ./docker/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
