services:
  php:
    build:
      context: .
      dockerfile: Dockerfile.php
      target: final
    networks:
      - dokploy-network
    env_file:
      - path: .env

  nginx:
    image: nginx
    ports:
      - "6969:80"
    volumes:
      - ./src:/var/www/html/src/
      - ./public:/var/www/html/public/
      - ./docker/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
    networks:
      - dokploy-network

networks:
  dokploy-network:
    external: true
