services:
  web:
    image: nginx:stable-alpine3.20-perl
    ports:
      - "80:80"
    volumes:
      - ./:/var/www/html
      - ./docker/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php

  php:
    image: php:8.2-fpm
    build: 
      dockerfile: php-fpm.Dockerfile
    volumes:
      - ./:/var/www/html